"use client";

import { getModalClassNames } from "@/lib/uiStyles";
import { cn } from "@/lib/utils";
import { getUserProfileAPI } from "@/container/profile/ProfileApis";
import getCookieData from "@/utils/getCookieData";
import {
  Button,
  Image,
  Modal,
  ModalBody,
  ModalContent,
  ModalFooter,
} from "@heroui/react";
import Cookies from "js-cookie";
import { ReactNode, RefObject, useEffect, useState } from "react";

export const PRINT_ROWS_PER_PAGE = 16;
export const PRINT_SPLIT_ROWS_PER_PAGE = 12;

export function chunkRows<T>(rows: T[] | undefined | null, size: number): T[][] {
  const list = rows ?? [];
  if (!list.length) return [[] as T[]];
  const pages: T[][] = [];
  for (let i = 0; i < list.length; i += size) {
    pages.push(list.slice(i, i + size));
  }
  return pages;
}

export function chunkPairedRows<L, R>(
  left: L[] | undefined | null,
  right: R[] | undefined | null,
  size: number,
) {
  const leftRows = left ?? [];
  const rightRows = right ?? [];
  const pageCount = Math.max(
    1,
    Math.ceil(Math.max(leftRows.length, rightRows.length) / size),
  );

  return Array.from({ length: pageCount }, (_, index) => ({
    left: leftRows.slice(index * size, (index + 1) * size),
    right: rightRows.slice(index * size, (index + 1) * size),
    isLast: index === pageCount - 1,
    startIndex: index * size,
  }));
}

export function getGeneratedOnLabel() {
  return new Date().toLocaleString("en-GB", {
    day: "2-digit",
    month: "2-digit",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
    hour12: true,
  });
}

function nameFromUnknown(value: unknown): string {
  return typeof value === "string" && value.trim() ? value.trim() : "";
}

function getNameFromJwt(token: string | null): string {
  if (!token) return "";

  try {
    const payloadPart = token.split(".")[1];
    if (!payloadPart) return "";

    const json = atob(payloadPart.replace(/-/g, "+").replace(/_/g, "/"));
    const payload = JSON.parse(json) as Record<string, unknown>;

    return (
      nameFromUnknown(payload.User_Name) ||
      nameFromUnknown(payload.user_name) ||
      nameFromUnknown(payload.name) ||
      nameFromUnknown(payload.unique_name) ||
      nameFromUnknown(payload.username) ||
      ""
    );
  } catch {
    return "";
  }
}

function cachePrintUserName(name: string) {
  if (!name) return;

  Cookies.set("waxCraftClientUserName", name, {
    expires: 7,
    secure: process.env.NODE_ENV === "production",
    sameSite: "Strict",
    path: "/",
  });
}

function getCachedPrintUserName() {
  return (
    getCookieData<string | null>("waxCraftClientUserName") ||
    getNameFromJwt(getCookieData<string | null>("waxCraftClientToken")) ||
    ""
  );
}

export function PrintFooter({
  pageNo,
  totalPages,
}: {
  pageNo: number;
  totalPages: number;
}) {
  const [userName, setUserName] = useState("");
  const [generatedOn, setGeneratedOn] = useState("");

  useEffect(() => {
    setGeneratedOn(getGeneratedOnLabel());

    const cachedName = getCachedPrintUserName();
    if (cachedName) {
      setUserName(cachedName);
      return;
    }

    let cancelled = false;

    getUserProfileAPI()
      .then((res) => {
        const name = nameFromUnknown(res.data?.details?.[0]?.User_Name);
        if (!cancelled && name) {
          cachePrintUserName(name);
          setUserName(name);
        }
      })
      .catch(() => {});

    return () => {
      cancelled = true;
    };
  }, []);

  return (
    <div className="mt-auto flex items-center justify-between gap-3 px-8 py-3 text-[11px] text-muted-foreground">
      <span className="min-w-0">
        Generated By : {userName || ""}
        {userName ? ", " : ""}
        Generated from : WaxCraft
      </span>
      <span className="shrink-0">
        Page {pageNo} of {totalPages}
      </span>
      <span className="shrink-0">
        Generated on : {generatedOn}
      </span>
    </div>
  );
}

export function PrintPreviewModal({
  isOpen,
  onOpenChange,
  printRef,
  documentTitle,
  onPrint,
  children,
}: {
  isOpen: boolean;
  onOpenChange: (open: boolean) => void;
  printRef: RefObject<HTMLDivElement | null>;
  documentTitle: string;
  onPrint: () => void;
  children: ReactNode;
}) {
  return (
    <Modal
      isOpen={isOpen}
      scrollBehavior="normal"
      placement="center"
      onOpenChange={onOpenChange}
      backdrop="blur"
      size="4xl"
      classNames={getModalClassNames("4xl")}
      hideCloseButton
      isDismissable={false}
    >
      <ModalContent>
        <ModalBody className="min-h-0 overflow-hidden pt-5">
          <div className="h-[min(70vh,600px)] w-full overflow-auto rounded-xl border border-black/[0.06] bg-[#F7F5F3]/60 p-3">
            <div className="mx-auto w-[210mm]" ref={printRef}>
              <style>{`
                @media print {
                  @page { size: A4; margin: 0; }
                  .print-report-page { page-break-after: always; break-after: page; }
                  .print-report-page:last-child { page-break-after: auto; break-after: auto; }
                }
              `}</style>
              {children}
            </div>
          </div>
        </ModalBody>
        <ModalFooter>
          <Button
            color="default"
            variant="flat"
            onPress={() => onOpenChange(false)}
            size="lg"
            radius="sm"
            className="w-32"
          >
            Cancel
          </Button>
          <Button
            color="primary"
            size="lg"
            radius="sm"
            className="w-32"
            onPress={onPrint}
            aria-label={`Print ${documentTitle}`}
          >
            Print
          </Button>
        </ModalFooter>
      </ModalContent>
    </Modal>
  );
}

export function PrintPage({
  children,
  pageNo,
  totalPages,
}: {
  children: ReactNode;
  pageNo: number;
  totalPages: number;
}) {
  return (
    <div className="print-report-page relative mx-auto mb-4 flex h-[297mm] w-[210mm] flex-col overflow-hidden rounded-2xl border border-black/[0.08] bg-white shadow-[0_8px_24px_rgba(15,23,42,0.06)] print:mb-0 print:rounded-none print:border-0 print:shadow-none">
      {children}
      <PrintFooter pageNo={pageNo} totalPages={totalPages} />
    </div>
  );
}

export function PrintOrgHeader({
  orgName,
  orgAddress,
  title,
  compact = false,
}: {
  orgName?: string | null;
  orgAddress?: string | null;
  title: string;
  compact?: boolean;
}) {
  return (
    <div className={cn("border-b border-black/[0.08] px-6", compact ? "py-3" : "py-5")}>
      <div className="flex items-center gap-4">
        <div
          className={cn(
            "relative flex shrink-0 items-center justify-center overflow-hidden rounded-xl bg-[#F7F5F3]",
            compact ? "h-12 w-12" : "h-[72px] w-[72px]",
          )}
        >
          <Image
            alt="Org Image"
            src="/orgImg.png"
            className="h-full w-full object-contain"
          />
        </div>
        <div className="min-w-0 flex-1">
          <p
            className={cn(
              "truncate font-semibold uppercase tracking-tight text-foreground",
              compact ? "text-base" : "text-xl",
            )}
          >
            {orgName}
          </p>
          <p className="mt-0.5 text-xs uppercase tracking-wide text-muted-foreground">
            {orgAddress}
          </p>
        </div>
      </div>
      <p className="mt-4 text-center text-sm font-semibold text-foreground">
        {title}
      </p>
    </div>
  );
}

export function PrintMetaGrid({
  items,
}: {
  items: { label: string; value?: string | number | null }[];
}) {
  return (
    <div className="grid grid-cols-2 gap-x-8 gap-y-2 border-b border-black/[0.08] bg-[#F7F5F3]/80 px-6 py-3 text-sm">
      {items.map((item) => (
        <p key={item.label}>
          <span className="font-semibold text-foreground">{item.label} :</span>{" "}
          <span className="text-muted-foreground">{item.value ?? ""}</span>
        </p>
      ))}
    </div>
  );
}

export const printTheadClass =
  "bg-[#F7F5F3] text-[10px] font-medium uppercase tracking-[0.14em] text-muted-foreground";
export const printThClass = "px-3 py-2.5 text-left";
export const printTdClass = "border-t border-black/[0.05] px-3 py-2 text-sm";
export const printTotalRowClass =
  "border-t border-black/[0.08] bg-[#F7F5F3] text-sm font-semibold";
